server:
  port: 80   # 80 端口被占用的话可以改成 9001 等

spring:
  application:
    name: cloud-consumer-order   # 服务名：注册到 Nacos 的名字
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}  # Nacos 地址（Docker 部署时环境变量指向 nacos:8848）
cloud-provider-payment:   # 注意：这里是被调用方的 spring.application.name
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule